OdeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.net.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.net.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OdeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.net.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Restaurants
{
    public class ClientRestaurantsModel : PageModel
    {

    }
}

OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        public Restaurant Restaurant { get; set; }

        public DeleteModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = restaurantData.GetRestaurantById(restaurantId);
            if(Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost(int restaurantId)
        {
            var restaurant = restaurantData.Delete(restaurantId);
            restaurantData.Commit();

            if (restaurant == null)
                return RedirectToPage("./NotFound");
            else
            {
                TempData["Message"] = $"{restaurant.Name} deleted.";
                return RedirectToPage("./List");
            }

        }
    }
}

OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        [TempData]
        public String Message { get; set; }
        public Restaurant Restaurant { get; set; }

        public DetailModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int RestaurantID)
        {
            Restaurant = restaurantData.GetRestaurantById(RestaurantID);

            if (Restaurant == null)
                return RedirectToPage("./NotFound");

            return Page();
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        private readonly IHtmlHelper htmlHelper;

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IRestaurantData restaurantData, IHtmlHelper htmlHelper)
        {
            this.restaurantData = restaurantData;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult OnGet(int? restaurantId)
        {
            if(restaurantId.HasValue)
            {
                Restaurant = restaurantData.GetRestaurantById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();

            }
            

            if(Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();

            return Page();
        }

        public IActionResult OnPost()
        {
            if(!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }

            if (Restaurant.Id > 0)
                restaurantData.Update(Restaurant);
            else
                restaurantData.AddRestaurant(Restaurant);

            TempData["Message"] = "Restaurant updated successfully";
            restaurantData.Commit();
            return RedirectToPage("./Detail", new { restaurantId = Restaurant.Id });
        }
    }
}

OdeToFood/Pages/Restaurants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.net.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        public string MyPropString { get; private set; }
        public IEnumerable<Restaurant> Restaurants { get; private set; }

        [BindProperty(SupportsGet = true)] public string SearchTerm { get; set; }

        private readonly IConfiguration configuration;
        private readonly IRestaurantData restaurantData;

        public ListModel(IConfiguration configuration, IRestaurantData restaurantData)
        {
            this.configuration = configuration;
            this.restaurantData = restaurantData;
        }

        public void OnGet()
        {
            MyPropString = configuration["Message"];

            Restaurants = restaurantData.GetRestaurantByName(SearchTerm);
       
        }
    }
}

OdeToFood/Pages/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Pages.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetRestaurantsCount();
            return View(count);
        }
    }
}

OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Hello world!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml
@page
@model OdeToFood.Pages.Restaurants.ClientRestaurantsModel
@{
}
<table class="table" id="restaurants">

</table>
@section Scripts{

    <environment exclude="Development">
        <script src="~\node_modules\datatables.net\js\jquery.dataTables.js"></script>
        <link href="~\node_modules\datatables.net-dt\css\jquery.dataTables.css" rel="stylesheet" />
        <script src="~\node_modules\datatables.net-dt\js\dataTables.dataTables.js"></script>
    </environment>
    <environment include="Development">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.0/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.0/datatables.min.js"></script>
    </environment>
    

    <script>
        $(function () {
            $.ajax("/api/restaurants/",
                { method: "get" })
                .then(function (response) {
                    $("#restaurants").dataTable({
                        data: response,
                        columns: [
                            { "data": "name" },
                            { "data": "location" },
                            { "data": "cuisine" }
                            ]
                    });
                });
        });
    </script>
}

OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restaurantId}"
@model OdeToFood.Pages.Restaurants.DeleteModel
@{
}

<h2>Delete!</h2>
<div class="alert alert-danger">
    <p>Are you sure you want to delete @Model.Restaurant.Name?</p>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a asp-page="List" class="btn btn-default">Cancel</a>
    </form>
</div>

OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:int}"
@model OdeToFood.Pages.Restaurants.DetailModel
@{

}
@if(Model.Message != null)
{
    <div class="alert alert-info">
        <p>
            @Model.Message
        </p>
    </div>
}
<h2>@Model.Restaurant.Name</h2>
<div>
    <p>Restaurant Id: @Model.Restaurant.Id</p>
    <p>Restaurant Location : @Model.Restaurant.Location</p>
    <p>Cuisine Type: @Model.Restaurant.Cuisine</p>
</div>

<a asp-page="./List" class="btn btn-default">
    <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Go back!
</a>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:int?}"
@model OdeToFood.Pages.Restaurants.EditModel
@{
}

<h2>Editing @Model.Restaurant.Name</h2>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location"></label>
        <input asp-for="Restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine" class="form-control"
                asp-items="Model.Cuisines">
        </select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

OdeToFood/Pages/Restaurants/List.cshtml
@page
@model Restaurants.ListModel
@{
}
<h1>Welcome to restaurants</h1>



<form method="get">
    <div class="input-group col-md-4">
        <input class="form-control py-2" type="search"
               asp-for="SearchTerm">
        <span class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </div>
</form>

<p>List of all the available restaurants:</p>

@foreach (var r in Model.Restaurants)
{
    <partial name="_Summary" model="r" />
}

<a asp-page="./Edit" class="btn btn-primary">Add new</a>

@section footer {
    <p>@Model.MyPropString</p>
}

OdeToFood/Pages/Restaurants/NotFound.cshtml
@page
@{
}

<h1>Restaurant not found</h1>
<p>
    <a asp-page="./List" class="btn btn-default">
        <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>
        See all restaurants...
    </a>
</p>

OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurant

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Model.Name</h3>
    </div>
    <div class="panel-body">
        <span>Location: @Model.Location</span>
        <span>Location: @Model.Cuisine</span>
    </div>
    <div class="panel-footer">
        <a class="btn btn-lg" asp-page="./Detail" asp-route-restaurantId="@Model.Id">
            <i class="fa fa-info" aria-hidden="true"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Edit" asp-route-restaurantId="@Model.Id">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Delete" asp-route-restaurantId="@Model.Id">
            <i class="fa fa-trash" aria-hidden="true"></i>
        </a>
    </div>
</div>

OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="well">
    There are @Model restaurants here. <a asp-page="/Restaurants/List">See them all!</a>
</div>

OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/font-awesome/Content/font-awesome.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <vc:restaurant-count></vc:restaurant-count>
        <div class="container">
            &copy; 2021 - tst - <a asp-area="" asp-page="/Privacy">Privacy</a> <br />
            @RenderSection("footer", false)
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>